import { generateScoreProjectionData } from '../calculate-score-projection-data'

jest.mock('../../../src/modules/settings/settings-service')
jest.mock('../../../src/modules/student-exams/student-exam-repository')
jest.mock('../../../src/modules/student-exam-scores/student-exam-scores-repository')

const scoreProjectionData = [
  {
    name: 'Physics',
    order: 1,
    scores: [
      {
        section_id: '11694003-af07-4017-b125-224cf0057780',
        scaled_score: 118,
        is_excluded_from_pts: false,
        id: '983f3b98-4b54-44e3-9f67-369380eeb6b4',
        completed_as: 1,
        title: 'EK-test',
        completed: true,
      },
      {
        scaled_score: 119,
        is_excluded_from_pts: false,
        id: null,
        completed_as: 2,
        title: '2nd',
        completed: false,
      },
      {
        scaled_score: 120,
        is_excluded_from_pts: false,
        id: null,
        completed_as: 3,
        title: '3rd',
        completed: false,
      },
      {
        title: '4th',
        scaled_score: 121,
        is_excluded_from_pts: false,
        id: null,
        completed_as: 4,
        completed: false,
      },
      {
        title: '5th',
        scaled_score: 122,
        is_excluded_from_pts: false,
        id: null,
        completed_as: 5,
        completed: false,
      },
      {
        title: '6th',
        scaled_score: 123,
        is_excluded_from_pts: false,
        id: null,
        completed_as: 6,
        completed: false,
      },
      {
        scaled_score: 130,
        is_excluded_from_pts: false,
        id: null,
        completed_as: null,
        title: 'Target',
        pts: 123,
        target_score: 130,
        completed: false,
      },
    ],
  },
  {
    name: 'CARS',
    order: 2,
    scores: [
      {
        section_id: '158cb932-0151-41d6-b0b3-138f2b5c6b55',
        scaled_score: 118,
        is_excluded_from_pts: false,
        id: '983f3b98-4b54-44e3-9f67-369380eeb6b4',
        completed_as: 1,
        title: 'EK-test',
        completed: true,
      },
      {
        scaled_score: 121,
        is_excluded_from_pts: false,
        id: null,
        completed_as: 2,
        title: '2nd',
        completed: false,
      },
      {
        scaled_score: 124,
        is_excluded_from_pts: false,
        id: null,
        completed_as: 3,
        title: '3rd',
        completed: false,
      },
      {
        title: '4th',
        scaled_score: 127,
        is_excluded_from_pts: false,
        id: null,
        completed_as: 4,
        completed: false,
      },
      {
        title: '5th',
        scaled_score: 130,
        is_excluded_from_pts: false,
        id: null,
        completed_as: 5,
        completed: false,
      },
      {
        title: '6th',
        scaled_score: 132,
        is_excluded_from_pts: false,
        id: null,
        completed_as: 6,
        completed: false,
      },
      {
        scaled_score: 131,
        is_excluded_from_pts: false,
        id: null,
        completed_as: null,
        title: 'Target',
        pts: 132,
        target_score: 131,
        completed: false,
      },
    ],
  },
  {
    name: 'Biology',
    order: 3,
    scores: [
      {
        section_id: 'd97ced67-224a-4de8-817c-5f045c02de88',
        scaled_score: 118,
        is_excluded_from_pts: false,
        id: '983f3b98-4b54-44e3-9f67-369380eeb6b4',
        completed_as: 1,
        title: 'EK-test',
        completed: true,
      },
      {
        scaled_score: 118,
        is_excluded_from_pts: false,
        id: null,
        completed_as: 2,
        title: '2nd',
        completed: false,
      },
      {
        scaled_score: 118,
        is_excluded_from_pts: false,
        id: null,
        completed_as: 3,
        title: '3rd',
        completed: false,
      },
      {
        title: '4th',
        scaled_score: 118,
        is_excluded_from_pts: false,
        id: null,
        completed_as: 4,
        completed: false,
      },
      {
        title: '5th',
        scaled_score: 118,
        is_excluded_from_pts: false,
        id: null,
        completed_as: 5,
        completed: false,
      },
      {
        title: '6th',
        scaled_score: 118,
        is_excluded_from_pts: false,
        id: null,
        completed_as: 6,
        completed: false,
      },
      {
        scaled_score: 131,
        is_excluded_from_pts: false,
        id: null,
        completed_as: null,
        title: 'Target',
        pts: 118,
        target_score: 131,
        completed: false,
      },
    ],
  },
  {
    name: 'Psych Soc',
    order: 4,
    scores: [
      {
        section_id: 'fe531bd3-7a2d-4306-85a5-4e3574260eff',
        scaled_score: 118,
        is_excluded_from_pts: false,
        id: '983f3b98-4b54-44e3-9f67-369380eeb6b4',
        completed_as: 1,
        title: 'EK-test',
        completed: true,
      },
      {
        scaled_score: 120,
        is_excluded_from_pts: false,
        id: null,
        completed_as: 2,
        title: '2nd',
        completed: false,
      },
      {
        scaled_score: 122,
        is_excluded_from_pts: false,
        id: null,
        completed_as: 3,
        title: '3rd',
        completed: false,
      },
      {
        title: '4th',
        scaled_score: 124,
        is_excluded_from_pts: false,
        id: null,
        completed_as: 4,
        completed: false,
      },
      {
        title: '5th',
        scaled_score: 126,
        is_excluded_from_pts: false,
        id: null,
        completed_as: 5,
        completed: false,
      },
      {
        title: '6th',
        scaled_score: 128,
        is_excluded_from_pts: false,
        id: null,
        completed_as: 6,
        completed: false,
      },
      {
        scaled_score: 130,
        is_excluded_from_pts: false,
        id: null,
        completed_as: null,
        title: 'Target',
        pts: 128,
        target_score: 130,
        completed: false,
      },
    ],
  },
  {
    name: 'total',
    order: null,
    scores: [
      {
        scaled_score: 472,
        is_excluded_from_pts: false,
        id: '983f3b98-4b54-44e3-9f67-369380eeb6b4',
        completed_as: 1,
        title: 'EK-test',
        completed: true,
      },
      {
        scaled_score: 478,
        is_excluded_from_pts: false,
        id: null,
        completed_as: 2,
        title: '2nd',
        completed: false,
      },
      {
        scaled_score: 484,
        is_excluded_from_pts: false,
        id: null,
        completed_as: 3,
        title: '3rd',
        completed: false,
      },
      {
        scaled_score: 490,
        is_excluded_from_pts: false,
        id: null,
        completed_as: 4,
        title: '4th',
        completed: false,
      },
      {
        scaled_score: 496,
        is_excluded_from_pts: false,
        id: null,
        completed_as: 5,
        title: '5th',
        completed: false,
      },
      {
        scaled_score: 501,
        is_excluded_from_pts: false,
        id: null,
        completed_as: 6,
        title: '6th',
        completed: false,
      },
      {
        scaled_score: 522,
        is_excluded_from_pts: false,
        id: null,
        completed_as: null,
        title: 'Target',
        pts: 501,
        target_score: 522,
        completed: false,
      },
    ],
  },
]

describe('calculate-score-projection-data', () => {
  it('calculates score projection data', async () => {
    const data = await generateScoreProjectionData({ id: '' }, '')

    expect(data).toEqual(scoreProjectionData)
  })
})
