export type Admin = {
  id: string,
  email: string,
  password: string,
  admin_role: string,
  is_active: boolean,
  deleted_at: string,
  password_reset_token: string,
  password_reset_token_created_at: string,
  name: string,
  created_at: string,
  can_manage_glossary: boolean,
  can_manage_flashcards: boolean,
  can_manage_videos: boolean,
  can_manage_content_questions: boolean,
  can_manage_exams: boolean,
  can_manage_students: boolean,
  can_manage_courses: boolean,
  can_manage_animations: boolean,
  can_manage_score_tables: boolean,
  can_manage_notifications: boolean,
  can_manage_course_topics: boolean,
}
