install("NLKNguyen/papercolor-theme")
install("ellisonleao/gruvbox.nvim")
install("romainl/Apprentice")
install("joshdick/onedark.vim")
install("EdenEast/nightfox.nvim")

install("catppuccin/nvim", { as = "eatppucing" })
install("rebelot/kanagawa.nvim")
install("rose-pine/neovim", { as = "rose-pine" })
install("folke/tokyonight.nvim")
install("tiagovla/tokyodark.nvim", { as = "tokyodark" })
install("navarasu/onedark.nvim")

install("andrew-george/telescope-themes")

install("miikanissi/modus-themes.nvim")
install("alexmozaidze/palenight.nvim")
install("scottmckendry/cyberdream.nvim")
install("ptdewey/darkearth-nvim")
install("uloco/bluloco.nvim")
install("slugbyte/lackluster.nvim")
install("0xstepit/flow.nvim")
install("Abstract-IDE/Abstract-cs")
install("tomasiser/vim-code-dark")
install("bluz71/vim-moonfly-colors")

configure(function ()
  local telescope = require('telescope')
  telescope.load_extension('themes')

  keys.map_all("<leader>t", "<Esc>:Telescope themes<CR>")
end)
