module.exports = [
  {
    type: 'select',
    name: 'value',
    message: 'Launch which job?',
    choices: [
      { title: 'Reschedule outdated calendar events', description: 'Move incomplete tasks and schedule them for today', value: 'rescheduleIncompleteEvents' },
      { title: 'Remove outdated exams', description: 'Remove student exams that are N days after the expiration date', value: 'removeOutdatedExams' },
      { title: 'Course expiration - 3 days before', description: 'Dispatch notifications about courses that will expire in three days', value: 'dispatchCourseExpirationThreeDays' },
      { title: 'Exam expiration - 2 days before', description: 'Dispatch notifications about exams that will expire in two days', value: 'dispatchExamExpirationTwoDays' },
      { title: 'Exam expiration - today', description: 'Dispatch notifications about exams that have expired today', value: 'dispatchExamExpiredToday' },
      { title: 'Score calculations enabled', description: 'Evaluate if should enable score calculations for types', value: 'evaluateScoreCalculationsEnabled' },
      { title: 'Calculate percentile rank', description: 'Make calculations for all exam types that have score evaluation enabled', value: 'calculatePercentileRank' },
      { title: 'Calculate student exam scores', description: 'Calculate all pending student exams scores that are valid for scoring', value: 'calculateStudentExamScores' },
      { title: 'Log daily Salty Bucks balance', description: 'Log daily Salty Bucks balance for all students (for dashboard graph)', value: 'logDailySaltyBucksBalance' },
      { title: 'Course expiration - now', description: 'Look for expired courses, update status and send email to user', value: 'updateExpiredStudentCourses' },
      { title: 'Copy unlocked books', description: 'Make a copy (archive) of all unlocked books', value: 'copyUnlockedBooks' },
      { title: 'Completion meter - temperature', description: 'Calculate temperature for all student courses', value: 'calculateTemperature' },
      { title: 'Completion meter - oil level', description: 'Calculate oil level for all student courses', value: 'calculateOilLevel' },
      { title: 'Remove old archived or soft deleted unlocked books', description: 'Remove archived or soft deleted unlocked books older than 3 months', value: 'deleteOldArchivedOrSoftDeletedUnlockedBooksCompletely' },
      { title: 'Calculate percentile ranks for exams', description: 'Calculates the scores for completed exams, based on exam_score_maps and exam_section_score_maps', value: 'calculatePercentileRanks' },
      { title: 'Send out notifications', description: 'Send out notifications that have to be sent ove the last five minutes', value: 'sendOutNotifications' },
      { title: 'Remove old notifications', description: 'Remove notifications that are older than 6 months', value: 'removeOldNotifications' },
      { title: 'Remove old student notifications', description: 'Remove student notifications that are older than 2 weeks', value: 'removeOldStudentNotifications' },
      { title: 'Remove first softly removed student course', description: 'Remove first softly removed student course', value: 'deleteFirstSoftlyRemovedStudentCourse' },
      { title: 'Remove outdated student accounts', description: 'Remove outdated student accounts', value: 'removeOutdatedAccounts' },
    ],
    initial: 0,
  },
]
